input {
  beats {
    port => 5044
  }
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [proto] == "LDAP" or [proto] == "ldap" {
    mutate { add_field => { "alert_risk" => "high" } }
  }
  if [proto] == "HTTP" {
    mutate { add_field => { "alert_risk" => "high" } }
  }
  geoip {
    source => "src"
    target => "geoip"
  }
  date {
    match => ["timestamp", "ISO8601"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "network-traffic-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
